config/routes.rb
Rails.application.routes.draw do
  get 'products_return_lines/create'
  get 'products_return_lines/update'
  get 'products_return_lines/delete'

  devise_for :users, controllers: { 
    registrations: 'users/registrations' 
  }

  resources :workers do
    resource :worker_bio, only: [:new, :create, :edit, :update]
  end

  resources :bios 

  resources :suppliers do
    resources :products, only: [:new]
    resources :buys, only: [:index, :create]
  end

  resources :products do
    member do
      patch :toggle_state
    end
    resources :inventory_movements, only: [:new, :create, :show] do
      collection do
        get :consulta  # Para manejar la consulta de movimientos de un producto específico
      end
    end
  end

  resources :inventory_movements, only: [:index]
  
  resources :buys do
    member do
      post :place_order
      patch :change_state
    end
    resources :buy_lines, only: [:create, :update, :destroy]
  end

  resources :receptions, only: [:index, :show] do
    member do
      patch :complete  # Acción para completar la recepción
    end
    resources :reception_lines, only: [:update, :destroy] do
      collection do
        post :create  # Acción para crear nuevas líneas de recepción
      end
    end
  end

  resources :reception_lines do
      resources :partial_deliveries, only: [:create, :destroy]
  end

  resources :partial_deliveries, only: [:create, :destroy]

  resources :customers

  resources :sells do
    get 'search_products', to: 'sells#search_products'
    member do
      patch :confirm
    end
    resources :sell_lines, only: [:create, :destroy] do
    end
  end

  resources :products_returns do
    resources :products_return_lines, only: [:create]
    member do
      post :confirm_return
    end
  end

  resources :products_return_lines, only: [:update, :destroy]

  root 'pages#home'
end

app/models/reception.rb
class Reception < ApplicationRecord
  belongs_to :user
  belongs_to :supplier
  belongs_to :buy
  has_many :reception_lines, dependent: :destroy
  has_many :partial_deliveries, dependent: :destroy

  enum state: { "Pedido": 0, "Entregado": 1, "Parcial": 2 }

end

app/controllers/receptions_controller.rb
class ReceptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reception, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @receptions = current_user.receptions.order(created_at: :desc)
    @filtered_receptions = filter_receptions(@receptions, params[:query])
    @user = current_user
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
    @reception_lines = @reception.reception_lines
    @partial_deliveries = @reception.partial_deliveries
    @partial_delivery = current_user.partial_deliveries.new
  end

  def create
    service = ReceptionCreationService.new(current_user, reception_params[:supplier_id], reception_params[:buy_id])
    @reception = service.call

    if @reception.persisted?
      redirect_to @reception, notice: 'Reception was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    service = ReceptionUpdateService.new(@reception, reception_params)

    if service.call
      redirect_to @reception, notice: 'Reception was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @reception.destroy
    redirect_to receptions_url, notice: 'Reception was successfully destroyed.'
  end

  def complete
    service = ReceptionCompletionService.new(@reception, current_user)
    service.call
    redirect_to @reception, notice: 'Reception was successfully completed.'
  end

  private

  def set_reception
    @reception = current_user.receptions.find(params[:id])
  end

  def reception_params
    params.require(:reception).permit(:supplier_id, :buy_id, :last_reception_date, :state)
  end

  def filter_receptions(receptions, query)
    if query.present?
      receptions.joins(:supplier).where(
        'suppliers.name ILIKE ? OR receptions.id::text ILIKE ? OR receptions.state ILIKE ?',
        "%#{query}%", "%#{query}%", "%#{query}%"
      )
    else
      receptions
    end
  end
end

app/helpers/receptions_helper.rb
module ReceptionsHelper

  def check_completed_lines
    @reception.reception_lines.all? { |line| line.state == "Entregado" }
  end
end

app/views/receptions/index.html.erb
<!-- app/views/receptions/index.html.erb -->
<h1>Entregas</h1>

<!-- Botón para mostrar/ocultar el filtro -->
<div class="mb-3">
  <button class="btn btn-secondary" id="toggleFilterButton">Filtro</button>
</div>

<!-- Formulario de filtro oculto por defecto -->
<div id="filterForm" class="mb-3" style="display: none;">
  <%= form_with url: receptions_path, method: :get, local: false do |f| %>
    <div class="input-group">
      <%= f.text_field :query, class: "form-control", placeholder: "Buscar..." %>
      <button class="btn btn-outline-primary" type="submit">Buscar</button>
    </div>
  <% end %>
</div>

<!-- Marco turbo para actualizar dinámicamente la tabla de recepciones -->
<%= turbo_frame_tag "receptions" do %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Proveedor</th>
          <th>Compra</th>
          <th>Estado</th>
          <th>Última entrega</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @filtered_receptions.each do |reception| %>
          <tr>
            <td><%= reception.supplier.commercial_name %></td>
            <td><%= link_to reception.buy.created_at.strftime("%d/%m/%Y"), @user.buys.find(reception.buy.id) %></td>
            <td><%= reception.state.titleize %></td>
            <td><%= reception.updated_at.strftime('%d-%m-%Y') %></td>
            <td>
              <%= link_to 'Mostrar', reception_path(reception), class: 'btn btn-info btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<!-- Script para mostrar/ocultar el filtro -->
<script>
  document.getElementById('toggleFilterButton').addEventListener('click', function() {
    var filterForm = document.getElementById('filterForm');
    filterForm.style.display = (filterForm.style.display === 'none') ? 'block' : 'none';
  });
</script>

app/views/receptions/show.html.erb
<%= turbo_frame_tag "reception_#{@reception.id}" do %>
  <h1>Entrega #<%= @reception.id %> Details</h1>
  <h3>Estado: <%= @reception.state %></h3>
  <div class="row">
    <div class="col-md-12">
      <%= turbo_frame_tag "reception_lines" do %>
        <div class="card mt-3">
          <div class="card-header">
            <h4>Productos a recibir</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped text-center">
                <thead>
                  <tr>
                    <th>Estado</th>
                    <th>Producto</th>
                    <th>Pedido</th>
                    <th>Entregado</th>
                    <th>Pendiente</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  <% @reception.reception_lines.each do |line| %>
                    <tr id="reception_line_<%= line.id %>">
                      <td><%= line.state %></td>
                      <td><%= link_to line.product.product_name, line.product %></td>
                      <td><%= line.quantity_to_receive %></td>
                      <td class="text-success"><%= line.quantity_received %></td>
                      <td class="text-danger"><%= line.quantity_to_receive - line.quantity_received %></td>
                      <% if line.state != 'Entregado' %>
                        <td>
                          <%= button_to 'Completo', reception_line_partial_deliveries_path(line), method: :post, class: 'btn btn-success' %>
                        <td>
                      <% else %>
                        <td class="text-success">Completado</td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer d-flex justify-content-end">
           
          </div>
        </div>
      <% end %>

      <%= render "partial_deliveries/partial_deliveries_table" %>
      <%= render "partial_deliveries/new_partial_delivery" %>

    </div>
  </div>
<% end %>