config/routes.rb
Rails.application.routes.draw do
  get 'products_return_lines/create'
  get 'products_return_lines/update'
  get 'products_return_lines/delete'

  devise_for :users, controllers: { 
    registrations: 'users/registrations' 
  }

  resources :workers do
    resource :worker_bio, only: [:new, :create, :edit, :update]
  end

  resources :bios 

  resources :suppliers do
    resources :products, only: [:new]
    resources :buys, only: [:index, :create]
  end

  resources :products do
    member do
      patch :toggle_state
    end
    resources :inventory_movements, only: [:new, :create, :show] do
      collection do
        get :consulta  # Para manejar la consulta de movimientos de un producto específico
      end
    end
  end

  resources :inventory_movements, only: [:index]
  
  resources :buys do
    member do
      post :place_order
      patch :change_state
    end
    resources :buy_lines, only: [:create, :update, :destroy]
  end

  resources :receptions, only: [:index, :show] do
    member do
      patch :complete  # Acción para completar la recepción
    end
    resources :reception_lines, only: [:update, :destroy] do
      collection do
        post :create  # Acción para crear nuevas líneas de recepción
      end
    end
  end

  resources :reception_lines do
      resources :partial_deliveries, only: [:create, :destroy]
  end

  resources :partial_deliveries, only: [:create, :destroy]

  resources :customers

  resources :sells do
    get 'search_products', to: 'sells#search_products'
    member do
      patch :confirm
    end
    resources :sell_lines, only: [:create, :destroy] do
    end
  end

  resources :products_returns do
    resources :products_return_lines, only: [:create]
    member do
      post :confirm_return
    end
  end

  resources :products_return_lines, only: [:update, :destroy]

  root 'pages#home'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :supplier
  has_many :buy_lines, dependent: :destroy
  has_many :sell_lines, dependent: :destroy
  has_many :reception_lines, dependent: :destroy
  has_many :inventory_movements, dependent: :destroy
  has_many :partial_deliveries, dependent: :destroy

  # Define enums for state
  enum state: { Activo: 0, Inactivo: 1 }

  # Validations
  validates :product_name, presence: true
  validates :buy_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :buy_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :stock, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :min_stock, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:toggle_state, :show, :edit, :update, :destroy]
  before_action :set_suppliers, only: [:new, :create, :edit]

  def index
    @products = if params[:q].present?
                  Product.includes(:supplier).where("name LIKE ? OR stock LIKE ? OR suppliers.commercial_name LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%").references(:suppliers)
                else
                  Product.includes(:supplier).where(supplier: current_user.suppliers)
                end
  end

  def show
    @buys = current_user.buys
    @sells = current_user.sells
    @user = current_user
    @deliveries = current_user.reception_lines
    @returns = current_user.products_return_lines
  end

  def new
    @product = Product.new
    @product.supplier_id = params[:supplier_id] if params[:supplier_id]
  end

  def create
    @product = current_user.products.build(product_params)
    service = ProductCreationService.new(@product)
    if service.call
      redirect_to products_path, notice: 'Product was successfully created.'
    else
      set_suppliers
      render :new
    end
  end

  def edit
  end

  def update
    if ProductService.update_product(@product, product_params)
      redirect_to products_path, notice: 'Product was successfully updated.'
    else
      set_suppliers
      render :edit
    end
  end

  def destroy
    ProductService.destroy_product(@product)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(@product)
      end
      format.html { redirect_to products_path, notice: 'Product was successfully deleted.' }
    end
  end

  def toggle_state
    @product.state == "Activo" ? @product.update(state: "Inactivo") : @product.update(state: "Activo")
    
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to products_path, notice: 'El estado del producto ha sido actualizado.' }
    end
  end

  private

  def set_product
    @product = current_user.products.find(params[:id])
  end

  def set_suppliers
    @suppliers = current_user.suppliers
  end

  def product_params
    params.require(:product).permit(:product_name, :buy_price, :sell_price, :stock, :min_stock, :state, :supplier_id, :product_description)
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def get_customer_name(sell)
    customer = @user.customers.find_by(sell.customer_id)
    "#{customer.name} #{customer.surname1} #{customer.surname2}"
  end

  def get_customer(sell)
    @user.customers.find_by(sell.customer_id)
  end

end

app/views/products/_buys_card.html.erb
<div class="accordion mt-3" id="accordionPreviousReturned">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Compras      
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionPreviousReturned">
      <div class="accordion-body">
        <%= turbo_frame_tag "buys" do %>
          <% if @buys.any? %>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Fecha</th>
                  <th>Estado</th>
                  <th colspan="2">Acciones</th>
                  </tr>
              </thead>
              <tbody>
                <% @buys.each do |buy| %>
                <tr>
                  <td><%= link_to buy.created_at.strftime("%d/%m/%Y"), buy %></td>
                  <% if buy.state != "Creado" %>
                    <td><%= link_to buy.state, get_reception(@user, buy), { title: get_reception(@user, buy).updated_at.strftime("%d/%m/%Y") } %></td>
                  <% else %>
                    <td><%= buy.state %></td>
                  <% end %>
                  <td>
                    <%= button_to 'Eliminar', buy_path(buy), method: :delete, data: { confirm: '¿Seguro que se desea eliminar esta compra?' }, class: 'btn btn-danger btn-sm' %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p>No se encontró ningún resultado</p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_deliveries_card.html.erb
<div class="accordion mt-3" id="accordionProductDeliveries">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingProductDeliveries">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseProductDeliveries" aria-expanded="true" aria-controls="collapseProductDeliveries">
        Entregas      
      </button>
    </h2>
    <div id="collapseProductDeliveries" class="accordion-collapse collapse" aria-labelledby="headingProductDeliveries" data-bs-parent="#accordionProductDeliveries">
      <div class="accordion-body">
        <%= turbo_frame_tag "deliveries" do %>
          <% if @buys.any? %>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Fecha</th>
                  <th>Estado</th>
                  <th colspan="2">Acciones</th>
                  </tr>
              </thead>
              <tbody>
                <% @deliveries.each do |delivery| %>
                <tr>
                  <td><%= link_to delivery.created_at.strftime("%d/%m/%Y"), delivery.reception %></td>
                  <% if delivery.state != "Creado" %>
                    <td><%= link_to delivery.state, delivery.reception %></td>
                  <% else %>
                    <td><%= delivery.state %></td>
                  <% end %>
                  <td>
                    <%= button_to 'Eliminar', reception_path(delivery), method: :delete, data: { confirm: '¿Seguro que se desea eliminarlo?' }, class: 'btn btn-danger btn-sm' %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p>No se encontró ningún resultado</p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>

  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :supplier_id, 'Supplier', class: 'form-label' %>
    <% if @supplier %>
      <%= form.hidden_field :supplier_id, value: @supplier.id %>
      <p><%= @supplier.commercial_name %></p>
    <% else %>
      <%= form.collection_select :supplier_id, current_user.suppliers, :id, :commercial_name, {}, { class: 'form-control' } %>
    <% end %>
  </div> 

  <div class="mb-3">
    <%= form.label "Nombre" %>
    <%= form.text_field :product_name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label "Precio del proveedor" %>
    <%= form.number_field :buy_price, step: '0.01', class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :stock %>
    <%= form.number_field :stock, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :min_stock %>
    <%= form.number_field :min_stock, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label "Descripción", class: 'form-label' %>
    <%= form.text_area :product_description, rows: 3, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :state, "Estado" %>
    <%= form.select :state, options_for_select(Product.states.keys.map { |state| [state.humanize, state] }, product.state), class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label "PVP" %>
    <%= form.number_field :sell_price, step: '0.01', class: 'form-control' %>
  </div>
  
  <div class="mb-3">
    <%= form.submit product.new_record? ? 'Crear Producto' : 'Actuaizar Producto', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/_products_card.html.erb
<div class=" card mt-4">
    <div class="card-header">
      <button id="toggle-products-button" class="btn btn-info btn-block">Productos</button>
    </div>
    <div id="products-section" style="display: none;" class="card-body">
      <div class="d-flex justify-content-between align-items-center my-3">
        <%= link_to 'Nuevo Producto', new_supplier_product_path(@supplier), class: 'btn btn-success' %>
      </div>
      <%= turbo_frame_tag "products" do %>
        <% if @products.any? %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Stock</th>
                <th>Estado</th>
                <th colspan="3">Acciones</th>
              </tr>
            </thead>
            <tbody>
              <% @products.each do |product| %>
                <tr>
                  <td><%= product.product_name %></td>
                  <td><%= product.stock %></td>
                  <td>
                    <%= form_with url: toggle_state_product_path(product, @supplier), method: :patch, data: { turbo_frame: dom_id(product) }, class: "d-inline" do %>
                      <div class="form-check form-switch form-check-success">
                        <%= check_box_tag 'state', '1', product.Activo?, class: 'form-check-input', onchange: 'this.form.submit()' %>
                      </div>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to 'Mostrar', product_path(product), class: 'btn btn-info btn-sm' %>
                  </td>
                  <td><%= link_to 'Editar', edit_product_path(product), class: 'btn btn-warning btn-sm' %></td>
                  <td><%= button_to 'Eliminar', product_path(product), method: :delete, data: { confirm: '¿Seguro que se desea eliminar este producto?' }, class: 'btn btn-danger btn-sm' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>No se encontró ningún resultado</p>
        <% end %>
      <% end %>
    </div>
  </div>

  
<script>

  document.getElementById('toggle-products-button').addEventListener('click', function(event) {
    event.preventDefault();
    var productsSection = document.getElementById('products-section');
    productsSection.style.display = productsSection.style.display === 'none' ? 'block' : 'none';
  });
  
  </script>

app/views/products/_returns_card.html.erb
<div class="accordion mt-3" id="accordionProductReturns">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingProductReturns">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseProductReturns" aria-expanded="true" aria-controls="collapseProductReturns">
        Entregas      
      </button>
    </h2>
    <div id="collapseProductReturns" class="accordion-collapse collapse" aria-labelledby="headingProductReturns" data-bs-parent="#accordionProductReturns">
      <div class="accordion-body">
        <%= turbo_frame_tag "returns" do %>
          <% if @returns.any? %>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Fecha</th>
                  <th>Estado</th>
                  <th colspan="2">Acciones</th>
                  </tr>
              </thead>
              <tbody>
                <% @returns.each do |returned| %>
                <tr>
                  <td><%= link_to returned.created_at.strftime("%d/%m/%Y"), returned.products_return %></td>
                  <% if returned.state != "Pendiente" %>
                    <td><%= link_to returned.state, returned.products_return %></td>
                  <% else %>
                    <td><%= returned.state %></td>
                  <% end %>
                  <td>
                    <%= button_to 'Eliminar', products_return_line_path(returned), method: :delete, data: { confirm: '¿Seguro que se desea eliminarlo?' }, class: 'btn btn-danger btn-sm' %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p>No se encontró ningún resultado</p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_sells_card.html.erb
 <div class="accordion mt-3" id="accordionProductSells">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingProductSells">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseProductSells" aria-expanded="true" aria-controls="collapseProductSells">
        Ventas      
      </button>
    </h2>
    <div id="collapseProductSells" class="accordion-collapse collapse" aria-labelledby="headingProductSells" data-bs-parent="#accordionProductSells">
      <div class="accordion-body">
        <%= turbo_frame_tag "sells" do %>
          <% if @sells.any? %>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Fecha</th>
                  <th>Cliente</th>
                </tr>
              </thead>
              <tbody>
                <% @sells.each do |sell| %>
                  <tr>
                    <td><%= link_to sell.created_at.strftime("%d/%m/%Y"), sell %></td>
                    <td><%= link_to get_customer_name(sell), get_customer(sell) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p>No se encontró ningún resultado</p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
 

app/views/products/destroy.turbo_stream.erb
<%= turbo_stream.remove @product %>

app/views/products/edit.html.erb
<h1>Editar Producto</h1>
<%= render 'form', product: @product %>
<%= link_to 'Volver', products_path, class: 'btn btn-secondary' %>

app/views/products/index.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1>Productos</h1>
    <div>
      <button id="filter-button" class="btn btn-info">Filtro</button>
      <%= link_to 'Nuevo', new_product_path, class: 'btn btn-success' %>
    </div>
  </div>

  <div id="filter-form" style="display: none;">
    <%= form_with(url: products_path, method: :get, local: true, data: { turbo_frame: 'products' }) do %>
      <div class="mb-3">
        <%= label_tag :q, 'Search', class: 'form-label' %>
        <%= text_field_tag :q, params[:q], class: 'form-control' %>
      </div>
      <%= submit_tag 'Buscar', class: 'btn btn-primary' %>
    <% end %>
  </div>

  <%= turbo_frame_tag 'products' do %>
    <% if @products.any? %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Proveedor</th>
            <th>Estado</th>
            <th COLSPAN="3">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= product.product_name %></td>
              <td><%= product.stock %></td>
              <td><%= link_to product.supplier.commercial_name, product.supplier %></td>
              <td>
                <%= form_with url: toggle_state_product_path(product), method: :patch, data: { turbo_frame: dom_id(product) }, class: "d-inline" do %>
                  <div class="form-check form-switch form-check-success">
                    <%= check_box_tag 'state', '1', product.Activo?, class: 'form-check-input', onchange: 'this.form.submit()' %>
                  </div>
                <% end %>
              </td>
              <td><%= link_to 'Mostrar', product, class: 'btn btn-primary btn-sm' %></td>
              <td><%= link_to 'Editar', edit_product_path(product), class: 'btn btn-warning btn-sm' %></td>
              <td><%= button_to 'Eliminar', product_path(product), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No se encontró ningún resultado</p>
    <% end %>
  <% end %>
</div>

<script>
  document.getElementById('filter-button').addEventListener('click', function(event) {
    event.preventDefault();
    var filterForm = document.getElementById('filter-form');
    if (filterForm.style.display === 'none') {
      filterForm.style.display = 'block';
    } else {
      filterForm.style.display = 'none';
    }
  });
</script>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form', product: @product, supplier: @supplier %>
<%= link_to 'Back', products_path, class: 'btn btn-secondary' %>

app/views/products/show.html.erb
<%= content_for :page_title, "Product Details" %>

<div class="container mt-4">
  <div class="card">
    <div class="card-header d-flex justify-content-between">
      <h3 class="card-title"><%= @product.product_name %></h3>
      <div>
        <%= link_to 'Editar', edit_product_path(@product), class: 'btn btn-warning' %>
        <%= button_to 'Eliminar', product_path(@product), method: :delete, data: { turbo_confirm: '¿Seguro que se desea eliminar este producto?' }, class: 'btn btn-danger' %>
      </div>
    </div>
    <div class="card-body">
      <div class="mb-3">
        <strong>Precio de compra:</strong>
        <p><%= @product.buy_price %> €</p>
      </div>

      <div class="mb-3">
        <strong>Stock:</strong>
        <p><%= @product.stock %></p>
      </div>

      <div class="mb-3">
        <strong>Stock mínimo:</strong>
        <p><%= @product.min_stock %></p>
      </div>

      <div class="mb-3">
        <strong>Precio de venta:</strong>
        <p><%= @product.sell_price %> €</p>
      </div>


      <div class="mb-3">
        <strong>Estado:</strong>
        <p><%= @product.state.humanize %></p>
      </div>

      <div class="mb-3">
        <strong>proveedor:</strong>
        <p><%= link_to @product.supplier.commercial_name, supplier_path(@product.supplier) %></p>
      </div>

    </div>
    <div class="card-footer text-center">
      <%= link_to 'Volver a Productos', products_path, class: 'btn btn-secondary' %>

    </div>
  </div>

  <%= render "products/buys_card" %>
  <%= render "products/deliveries_card" %>
  <%= render "products/sells_card" %>
  <%= render "products/returns_card" %>

 </div>
  
 

app/views/products/toggle_state.turbo_stream.erb
<%= turbo_stream.replace @product do %>
  <tr id="<%= dom_id(@product) %>">
    <td><%= @product.product_name %></td>
    <td><%= @product.stock %></td>
    <td><%= link_to @product.supplier.commercial_name, @product.supplier %></td>
    <td>
      <%= form_with url: toggle_state_product_path(@product), method: :patch, data: { turbo_frame: dom_id(@product) }, class: "d-inline" do %>
        <div class="form-check form-switch">
          <%= check_box_tag 'state', '1', @product.Activo?, class: 'form-check-input', onchange: 'this.form.submit()' %>
          <label class="form-check-label"><%= @product.state %></label>
        </div>
      <% end %>
    </td>
    <td><%= link_to 'Mostrar', @product, class: 'btn btn-primary btn-sm' %></td>
    <td><%= link_to 'Editar', edit_product_path(@product), class: 'btn btn-warning btn-sm' %></td>
    <td><%= button_to 'Eliminar', product_path(@product), method: :delete, data: { turbo_method: :delete, turbo_confirm: '¿Estás seguro?' }, class: 'btn btn-danger btn-sm' %></td>
  </tr>
<% end %>